### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by NikoVP** [mewmew/arch#1]
Hello mewmew,
Sorry for creating this issue but couldn't find any other way of contacting you, and I've been told by devolutionX devs, you lurk around here. I am a contributor to the project, not as a programmer but as graphic design/concept artist. I've been told that you have a tool/script that extracts/exports diablo assets to png's. I would like to try my luck doing some work on the sprites and other assets but the tools available on the net aren't really that great, and lots of the resources I try to access are corrupted. So if there is any possibility you can help with that, I am usually at the DevilutionX discord, under the name BillieJoe. Thganks in advance.
Nikolai

**Comment by mewmew** [comment]
Hi Nikolai,
Added you on Discord :)
